export interface ExternshipData {
  "Externship Site Name": string;
  "Which year did/ will you graduate/ complete your externship?": string;
  "Is/was your externship in the US?": string;
  "If not, where was your externship located?": string;
  "City of Externship?": string;
  "Externship State or Territory?": string;
  "Duration of Externship?": string;
  "Number of days per week?": string;
  "Hours per day?": string;
  "Was compensation provided?": string;
  "Annual Compensation:": string;
  "How was compensation distributed?": string;
  "Does the student get health insurance or other benefits?": string;
  "How many preceptors do you have?": string;
  "Preceptors and CCC-A:": string;
  "Preceptor's background": string;
  "Feedback style of preceptors": string;
  "How supported did you feel during the externship?": string;
  "The clinic population is mainly Pediatric-focused (80% or more Pediatrics)": string;
  "The clinic population is mainly Adult-pediatric (80% or more Adults)": string;
  "The clinic population is mix of adult and pediatric": string;
  "The clinic population is only adults": string;
  "The clinic population is other": string;
  "How diverse is the clientele?": string;
  "Predominantly which population is seen in the clinic": string;
  "How diverse is the clientele (socioeconomics)?": string;
  "Predominantly which population is seen in the clinic (socioeconomics)?": string;
  "Does the clinic have rotations for specialties such as vestibular, cochlear implants, etc": {
    "?": string;
  };
  "Please provide more details about each rotation": string;
  "Routine audiological testing (Audiometry +immittance):": string;
  "Frequency": string;
  "HA Consultation": string;
  "HA Fitting": string;
  "HA Follow up": string;
  "ABR": string;
  "Other electrophysiological measures": string;
  "OAEs": string;
  "CPA": string;
  "VRA": string;
  "CAPD Testing": string;
  "Tinnitus Evalulation": string;
  "Tinnitus Management": string;
  "Vestibular testing": string;
  "Vestibular Rehabilitation": string;
  "CI Evaluation": string;
  "CI activation and follow up": string;
  "Aural Rehabilitation": string;
  "Group Rehabiliation": string;
  "IOM": string;
  "Other experiences and frequency": string;
  "How long does the student shadow their preceptor(s)?": string;
  "After what duration are students independent (see patients by themselves without supervisor in the room)?": string;
  "Do students have independent schedules?": string;
  "Number of sites and student placement in each site: Which of the following is true about the site:": string;
  "Are hearing aid technicians or other staff available for support?": string;
  "Which professionals does the clinic routinely collaborate with (daily or multiple times a week)?": string;
  "How often are meetings conducted with interprofessional colleagues?": string;
  "How often are meetings held within the department?": string;
  "What is the extern’s expected contribution to the meetings?": string;
  "Are research opportunities available?": string;
  "Is research required?": string;
  "Is there time allotted for research or is it something on top of clinical hours?": string;
  "Research opportunities involve:": string;
  "Is time off provided to attend conferences?": string;
  "Are there continuing education opportunities?": string;
  "Where is / was the externship advertised?": string;
  "What is the specialty/ most attractive feature of this externship?": string;
  "What are the weaknesses of this externship?": string;
  "Details about lunch breaks": string;
  "Is the externship site looking to hire students post-externship?": string;
  "What is the cost of living in the area?": string;
  "Is there affordable housing in the area and how is it found?": string;
  field92: string;
  field93: string;
  field94: string;
  field95: string;
  field96: string;
  field97: string;
  field98: string;
  field99: string;
  field100: string;
  field101: string;
}
